############################### Youre device configuration
esphome:
  name: ESPhome_paj7660
  friendly_name: "ESPhome PAJ7660"

esp32:
  board: esp32-c5-devkitc-1
  framework:
    type: esp-idf

wifi:
etc.........

############################## Configuration for PAJ7660
external_components:
  - source:
      type: local
      path: components

i2c:
  scl: GPIO5 # Change for your setup
  sda: GPIO4 # Change for your setup
  scan: true
  frequency: 200kHz
  id: i2c_bus

pag7660v2:
  id: my_gesture_sensor
  address: 0x68
  i2c_id: i2c_bus

text_sensor:
  - platform: pag7660v2
    gesture:
      name: "Gesture Sensor"
      
sensor:
  - platform: pag7660v2
    rotation:
      name: "Gesture Rotation Step"
      unit_of_measurement: "°"
